# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7d61cf8fc7a63e712a637d63da7186ff7ec8a31295a3ff3873b96ef62f32dddbc2a595e76ab64035447a6385adb247aaffd1a8c34fd766e0a7aaf4477147c72

test:
  secret_key_base: 22d9a4276a6d0776352c5e79e0e96cbe3a49f9ae9985f6189f6a851bec91dffa4c05669e9b57d076fa5ab8696d8408c146f189a9dd32d22f73c5ffc9a8bdb8ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
